name: Coode style

on:
  push:
    branches: [ master, develop, feature/*, hotfix/*, release/* ]

jobs:
  checkers:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - checker: pylint
            args: poom
          - checker: flake8
            args: .
          - checker: mypy
            args: .
          - checker: black
            args: --check .
          - checker: pydocstyle
            args: poom
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            .mypy_cache
            ~/.cache/pip
          key: "${{ matrix.checker }}"
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
            python -m pip install -U pip
            python -m pip install -U -r dev_requirements.txt
      - name: "Run ${{ matrix.checker }}"
        run: "${{ matrix.checker }} ${{ matrix.args }}"
